"""cambie nombre tabla de productos_model a productos

Revision ID: 98b0135596bb
Revises: f9d7ba45aee6
Create Date: 2024-11-29 20:30:54.978645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b0135596bb'
down_revision = 'f9d7ba45aee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.rename_table
    op.rename_table('producto_model', 'productos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('productos', 'producto_model')
    # ### end Alembic commands ###
