"""agregue columna fecha vencimiento

Revision ID: f9d7ba45aee6
Revises: bf05f5c4e306
Create Date: 2024-11-29 20:23:18.938178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d7ba45aee6'
down_revision = 'bf05f5c4e306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
        batch_op.alter_column('precio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_model', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('fecha_vencimiento')

    # ### end Alembic commands ###
